name: Dependabot auto-approve and automerge
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: write

jobs:
  approve-and-enable-automerge:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge on PR
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
